// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr4GfJ1ZfUz58cOhsEXwNRW7v_dXQrkwA',
    appId: '1:832607352005:web:8be5918c8c472ce646acac',
    messagingSenderId: '832607352005',
    projectId: 'weddingplanner-89486',
    authDomain: 'weddingplanner-89486.firebaseapp.com',
    storageBucket: 'weddingplanner-89486.firebasestorage.app',
    measurementId: 'G-CM6FYFZ1T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBijIJ6H8gRSQ05T5GfYrlCMx_35YtwGew',
    appId: '1:832607352005:android:16dc1dd56497601e46acac',
    messagingSenderId: '832607352005',
    projectId: 'weddingplanner-89486',
    storageBucket: 'weddingplanner-89486.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0q8dIsreSG6vxt-2Rs8ScvSW54resxsU',
    appId: '1:832607352005:ios:b88be9b4e009290646acac',
    messagingSenderId: '832607352005',
    projectId: 'weddingplanner-89486',
    storageBucket: 'weddingplanner-89486.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0q8dIsreSG6vxt-2Rs8ScvSW54resxsU',
    appId: '1:832607352005:ios:b88be9b4e009290646acac',
    messagingSenderId: '832607352005',
    projectId: 'weddingplanner-89486',
    storageBucket: 'weddingplanner-89486.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr4GfJ1ZfUz58cOhsEXwNRW7v_dXQrkwA',
    appId: '1:832607352005:web:b0f4fde8469aecdd46acac',
    messagingSenderId: '832607352005',
    projectId: 'weddingplanner-89486',
    authDomain: 'weddingplanner-89486.firebaseapp.com',
    storageBucket: 'weddingplanner-89486.firebasestorage.app',
    measurementId: 'G-SRQHKZEDC6',
  );
}
